spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_schema: "demo"
  datasource:
    generate-unique-name: false
    url: "jdbc:postgresql://${API_URL}:5436/postgres?currentSchema=demo"
    username: "postgres"
    password: "password"
    driverClassName: org.postgresql.Driver
server:
  port: 8080
  forward-headers-strategy: framework
springdoc:
  swagger-ui:
    url: unleash.spec.yaml
    path: /
unleash:
  url: http://localhost:4242/api/
  apikey: default:development.unleash-insecure-api-token
